version: '3.4'

services:
  voice-registry:
    build: .
    volumes:
      - .:/usr/src/app
      - ./temp:/usr/src/app/temp
      - ./storage:/usr/src/app/storage
      - ./voice_registry/templates:/usr/src/app/templates
      - ./static:/usr/src/app/static
    ports:
      - 80:80
